### ISSUE TITLE
Unresolved paths when building locally

### ISSUE THREAD

**Issue by pshriwise** [iwazaru/road-trips#38]
Hi @iwazaru! I came across this really nifty project today and wanted to give it a whirl. Apologies for bothering you with an issue if this is a side project and you aren't really looking to address outsider questions.

I followed the instructions in the README as best I could, but I'm having trouble building this site locally. The fist modification I made was to insert my own Google Maps API key in `Maps.js` but there were still a lot of images that still aren't loading successfully when I build the site with `yarn build`. When I try `yarn start` I get a 404 with a warning about a static path. A presented link takes me to a FAQ on static paths and how to resolve them but none of the solutions seemed to help. I'm not really a web dev, so at this point I'm a bit stuck.

Any thoughts?

**Comment by iwazaru** [comment]
Hey @pshriwise, thanks for reaching out. This is indeed a personal side-project and I haven't given much thought about reusability, but I'm glad it could be useful to other people (that's why it's on Github!) so I'll do my best to help!

For starter, it looks like thoughtless dependency updates have broken the build. I'll have a look at soon as possible.

**Comment by iwazaru** [comment]
@pshriwise can you pull the master branch, reinstall dependencies with `yarn` and try `yarn start` again? I have updated a few dependencies and it should have fixed the 404 problem.

Also, can you tell me if you still have the image loading issue when using `yarn build`? I can't reproduce it so I think it might have been related to the first problem.

**Comment by pshriwise** [comment]
Looks like those updates did the trick! Thank you! Any suggestions for contributions as I start playing with this? Looks like there's a project going I could pull tasks from?

**Comment by iwazaru** [comment]
Great! I'll close the issue as this particular problem is solved.

I've added [instructions in the README](https://github.com/iwazaru/road-trips#create-your-own-travel-blog-using-road-trips) on how to change the blog content from a fork, if you need them. Please open new issues if anything seems to be missing or feels unclear.

About contributions, I welcome them of course. The project and its tasks were created a long time ago, before my trip to Scotland in 2018 and I haven't thought about since, as the blog went stale. Please prioritize any contributions you feel would be useful to you. Even if they are not listed in the GitHub project, I'm open to suggestions!
